- name: DEBUG data_mount_target
  debug:
    msg: "VARS: echo {{ data_mount_target }}"

- name: DEBUG ecr_url
  debug:
    msg: "VARS: echo {{ ecr_url }}"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ app_install_root }}/{{ app_repo_name }}"
    restarted: true
    build: yes
    recreate: always
    nocache: yes
  register: output

- ansible.builtin.debug:
    var: output
