- name: FIRST LOG
  command: env

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

  gather_facts: false
  vars:
    test_var1: A
    test_var2: "{{ test_var1 }}"
  tasks:
    - debug:
        var: vars

- name: Log variables ECR_URL
  block:
    - debug:
        var: ECR_URL

- name: DEBUG ENV
  debug:
    msg: "VARS: echo $(env)"

- name: DEBUG ENV
  debug:
    msg: "VARS: echo env"

- name: Log All Variables env
  command: "env"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ app_install_root }}/{{ app_repo_name }}"
    restarted: true
    build: yes
    recreate: always
    nocache: yes
  register: output

- ansible.builtin.debug:
    var: output
