- name: FIRST LOG
  command: env

- name: Log variables ECR_URL
  block:
    - debug:
        var: ECR_URL

- name: DEBUG ENV
  debug:
    msg: "VARS: echo $(env)"

- name: DEBUG ENV
  debug:
    msg: "VARS: echo env"

- name: Log All Variables env
  command: "env"

- name: Start docker-compose
  docker_compose:
    project_src: "{{ app_install_root }}/{{ app_repo_name }}"
    restarted: true
    build: yes
    recreate: always
    nocache: yes
  register: output

- ansible.builtin.debug:
    var: output
